pipeline {
    agent any
    tools {
        maven 'maven2'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package -Denforcer.fail=false'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Denforcer.fail=false'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('new pipeline_2 check') {
            steps {
                echo 'new pipeline_2 check completed now'
            }
        }
    }
}
